#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'utopianTree' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#
def length(n):
    if n==0:
        return 1
    elif n==1:
        return 2
    if n%2==0:
        return length(n-1)+1
    else:
        return length(n-1)*2
def utopianTree(n):
    # Write your code here
    return length(n)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
